project:
  type: website
  output-dir: ../

format: 
    revealjs: 
        theme: dark
        mainfont: monospace
        slide-number: true
        show-slide-number: all
        mermaid:
            theme: neutral
            
execute:
    echo: false
